---
apiVersion: v1
kind: Service
metadata:
  name: flink
  labels:
    app: flink
spec:
  ports:
  - port: 6123
    name: rpc
  - port: 6124
    name: blob
  - port: 6125
    name: query
  - port: 8081
    name: ui
  clusterIP: None
  selector:
    app: flink
---
kind: Service
apiVersion: v1
metadata:
  name: flink-jobmanager-0
spec:
  type: NodePort
  ports:
    - port: 9249
      name: prom
      nodePort: 31222
    - port: 8081
      name: ui
      nodePort: 31111
  selector:
    statefulset.kubernetes.io/pod-name: flink-jobmanager-0
---
kind: Service
apiVersion: v1
metadata:
  name: flink-taskmanager
spec:
  type: NodePort
  ports:
    - port: 9249
      name: prom
      nodePort: 31333
  selector:
    app: flink
    component: taskmanager
---