apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-jobmanager
spec:
  selector:
    matchLabels:
      app: flink
  serviceName: "flink"
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      hostAliases:
      - ip: "$hdfs-node-ip"
        hostnames:
        - "hdfs-node-hostname"
      containers:
      - name: jobmanager
        image: gokcesurenkok/flink_hadoop_prometheus:v1.9-scala_2.12
        workingDir: /opt/flink
        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/jobmanager.sh start;\
          while :;
          do
            if [[ -f $(find log -name '*jobmanager*.log' -print -quit) ]];
              then tail -F -n +1 log/*jobmanager*.log;
            fi;
          done"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 8081
          name: ui
        - containerPort: 9249
          name: prom
        livenessProbe:
          httpGet:
            path: /overview
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: hadoop-config-volume
          mountPath: /etc/hadoop
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j.properties
            path: log4j.properties
      - name: hadoop-config-volume
        configMap:
          name: hadoop-config
          items:
          - key: core-site.xml
            path: core-site.xml
          - key: hdfs-site.xml
            path: hdfs-site.xml

